views/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required
from models import User
from db import db

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")
        user = User.query.filter_by(username=username).first()
        if user and check_password_hash(user.password, password):
            login_user(user)
            return redirect(url_for('start_page'))
        else:
           error = "Benutzername oder Passwort ist nicht korrekt!"
    return render_template("login.html",error=error)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['new_username']
        password = request.form['new_password']

        # Überprüfen, ob der Benutzername bereits existiert
        existing_user = User.query.filter_by(username=username).first()
        if existing_user:
            error_message = "Dieser Benutzername ist bereits vergeben."
            return render_template('login.html', register_error=error_message)

        # Hashen des Passworts und Erstellen eines neuen Benutzers
        hashed_password = generate_password_hash(password)
        new_user = User(username=username, password=hashed_password)
        db.session.add(new_user)
        db.session.commit()

        return redirect(url_for('auth.login'))

    return render_template('login.html')

templates/edit_ccv.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EDIT LTC </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>

    <title>EDIT-CCV-VALUE</title>

</head>

<div class="container mt-5">
    <h2>Code Change Volume Editing</h2>


    <form class="container" method="POST" action="{{ url_for('update_ccv', ccv_id=metric.id) }}">
        <div class="form-group">
            <label for="timestampInput">Timestamp:</label>
            <input type="datetime-local" class="form-control" id="timestampInput" name="timestamp"
                value="{{ metric.timestamp.strftime('%Y-%m-%dT%H:%M') }}">
        </div>
        <div class="form-group">
            <label for="ccvInput">Code Change Volume:</label>
            <input type="number" class="form-control" id="ccvInput" name="ccvValue"
                value="{{ metric.code_change_volume }}">
        </div>

        <button type="submit" class="btn btn-primary">Save changes</button>
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</html>

templates/edit_ltc.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EDIT LTC </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
    <title>EDIT-LTC-VALUE</title>

</head>

<div class="tab-pane container mt-5" id="editLeadTimeForChange">
    <h2>Lead Time for Changes Editing</h2>

    <!-- Formular zum Bearbeiten von Commit- und Deployment-Daten -->
    <form id="editLtcForm" method="POST" action="/update_ltc/{{ ltc.id }}">
        <!-- Commit Datum und Uhrzeit -->
        <div class="form-group">
            <label for="editCommitDatetime">Commit date and time:</label>
            <input type="datetime-local" class="form-control" id="editCommitDatetime" name="commit_datetime"
                value="{{ ltc.commit_datetime.isoformat() }}">
        </div>

        <!-- Deployment Datum und Uhrzeit -->
        <div class="form-group">
            <label for="editDeploymentDatetime">Deployment date and time:</label>
            <input type="datetime-local" class="form-control" id="editDeploymentDatetime" name="deployment_datetime"
                value="{{ ltc.deployment_datetime.isoformat() }}">
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <label class="input-group-text" for="editInputGroupSelect01">Capture for the project:</label>
            </div>
            <select id="editLtcprojectSelector" name="project_id" class="custom-select">
                <option value="all" {% if ltc.projekt_id==None %}selected{% endif %}>All projects</option>
                {% for project in projects %}
                <option value="{{ project.id }}" {% if ltc.projekt_id==project.id %}selected{% endif %}>{{ project.name
                    }}</option>
                {% endfor %}
            </select>
        </div>

        <div>
            <label>Deployment status:</label>
            <input type="radio" id="editSuccess" name="deployment_status" value="true" {% if ltc.deployment_successful
                %}checked{% endif %}>
            <label for="editSuccess">Successful</label>

            <input type="radio" id="editFailure" name="deployment_status" value="false" {% if not
                ltc.deployment_successful %}checked{% endif %}>
            <label for="editFailure">Failed</label>
        </div>

        <button type="submit" class="btn btn-primary">Save changes</button>
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>

<script src="/static/js/main.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</html>

templates/edit_mttr.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EDIT MTTR </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>

    <title>EDIT-MTTR-VALUE</title>


</head>

<div class="container mt-5">
    <h2>Edit Mean Time To Recover</h2>

    <!-- Formular zum Bearbeiten von MTTR-Daten -->
    <form action="{{ url_for('update_mttr', incident_id=incident.id) }}" method="post">
        <div class="form-group">
            <label for="start_time">Startzeit:</label>
            <input type="datetime-local" id="start_time" name="start_time" class="form-control" value="{{ incident.start_time.strftime('%Y-%m-%dT%H:%M') }}" required>
        </div>

        <div class="form-group">
            <label for="end_time">Endzeit:</label>
            <input type="datetime-local" id="end_time" name="end_time" class="form-control" value="{{ incident.end_time.strftime('%Y-%m-%dT%H:%M') }}" required>
        </div>

        <div class="form-group">
            <label for="description">Beschreibung:</label>
            <textarea id="description" name="description" class="form-control" rows="3" required>{{ incident.description }}</textarea>
        </div>

        <div class="form-group">
            <label for="cause">Ursache:</label>
            <input type="text" id="cause" name="cause" class="form-control" value="{{ incident.cause }}" required>
        </div>

        <div class="form-group">
            <label for="resolution">Lösung:</label>
            <input type="text" id="resolution" name="resolution" class="form-control" value="{{ incident.resolution }}" required>
        </div>

        <div class="form-group">
            <label for="project_id">Projekt-ID:</label>
            <select id="project_id" name="project_id" class="form-control">
                {% for project in projects %}
                <option value="{{ project.id }}" {% if project.id == incident.projekt_id %} selected {% endif %}>{{ project.name }}</option>
                {% endfor %}
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Aktualisieren</button>
    </form>

    <a href="{{ url_for('start_page') }}" class="btn btn-secondary mt-3">Zurück zur Startseite</a>
</div>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="de">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PAnDORA Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/loginStyle.css') }}">

</head>

<body>
    <div class="login-container">
        <div class="login-header">
            <div class="text-container">
                <h2>PAnDORA</h2>
                <p>Performance Analyzer for DORA Metrics</p>
            </div>
            <img src="{{ url_for('static', filename='images/NewPandoraLogo.png') }}" alt="PanDORA Logo" class="logo">
        </div>
        <form class="login-form" method="POST" action="{{ url_for('auth.login') }}">
            <input type="text" id="username" name="username" placeholder="Username" required>
            <input type="password" id="password" name="password" placeholder="Password" required>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
        <!-- Button zum Öffnen des Registrierungsmodals -->
        <div class="container mt-4">
            <h3>No account yet?</h3>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#registerModal">
                Register here
            </button>
        </div>
    </div>




    <!-- Modal -->
    <div class="modal fade" id="errorModal" tabindex="-1" aria-labelledby="errorModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="errorModalLabel">Login error</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Username or password is not correct!
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Registrierungsmodal -->
    <div class="modal fade" id="registerModal" tabindex="-1" aria-labelledby="registerModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="registerModalLabel">Create new Account</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form class="register-form" method="POST" action="{{ url_for('auth.register') }}">
                        {% if register_error %}
                        <div class="alert alert-danger">
                            {{ register_error }}
                        </div>
                        {% endif %}
                        <input type="text" id="new_username" name="new_username" placeholder="Benutzername" required>
                        <input type="password" id="new_password" name="new_password" placeholder="Passwort" required>
                        <button type="submit" class="btn btn-primary">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Auslagern in JS -->
    {% if error %}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var errorModal = new bootstrap.Modal(document.getElementById('errorModal'));
            errorModal.show();
        });
    </script>
    {% endif %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

    {% if register_error %}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var registerModal = new bootstrap.Modal(document.getElementById('registerModal'));
            registerModal.show();
        });
    </script>
    {% endif %}



</body>

</html>